# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 11, 7, 9, 13, 586089, tzinfo=utc)),
        ),
    ]
